"""create sections, achievements, images, badges, badges_card

Revision ID: 3ee9ad7600f1
Revises: 00c67b7a5799
Create Date: 2025-02-07 19:15:13.279061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee9ad7600f1'
down_revision: Union[str, None] = '00c67b7a5799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badges'))
    )
    op.create_table('sections',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sections'))
    )
    op.create_table('achievements',
    sa.Column('table_name', sa.String(), server_default='achievements', nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_desktop', sa.String(), nullable=True),
    sa.Column('image_mobile', sa.String(), nullable=True),
    sa.Column('image_alt', sa.String(), nullable=True),
    sa.Column('button_text', sa.String(), nullable=True),
    sa.Column('button_url', sa.String(), nullable=True),
    sa.Column('order_value', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_achievements_section_id_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements'))
    )
    op.create_index(op.f('ix_achievements_order_value'), 'achievements', ['order_value'], unique=False)
    op.create_table('card_badge_achievement',
    sa.Column('card_badge_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name=op.f('fk_card_badge_achievement_achievement_id_achievements')),
    sa.ForeignKeyConstraint(['card_badge_id'], ['badges.id'], name=op.f('fk_card_badge_achievement_card_badge_id_badges')),
    sa.PrimaryKeyConstraint('card_badge_id', 'achievement_id', name=op.f('pk_card_badge_achievement'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_badge_achievement')
    op.drop_index(op.f('ix_achievements_order_value'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_table('sections')
    op.drop_table('badges')
    # ### end Alembic commands ###
