services:
  web:
    build: .
    container_name: fastapi_landing
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./app/env/.env

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: